# Generated by Django 4.1.1 on 2022-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='designation',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x1049b3ac0>', max_length=100),
        ),
    ]
