# Generated by Django 4.1.1 on 2022-10-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_engine_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
