# Generated by Django 4.1.1 on 2022-10-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_tires'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tires',
            new_name='Tire',
        ),
    ]
